### ISSUE TITLE
Some incorrect things I've noticed

### ISSUE THREAD

**Issue by Talon1024** [jekyllgrim/ZScript_Basics#1]
In "[Classes Instead of Actors](https://github.com/jekyllgrim/ZScript_Basics/blob/master/Classes_instead_of_actors.md)", it says you can't have a class that inherits from nothing. This isn't true; The Le_ProjScreen class [from Libeye](https://github.com/Realm667/WolfenDoom/blob/master/scripts/libraries/libeye/projector.txt) inherits from nothing, but then again, it isn't an actor.

In "[Anonymous Functions](https://github.com/jekyllgrim/ZScript_Basics/blob/master/Anonymous_functions.md)", it says you need to include a pair of empty parentheses at the end to call a function. No, you don't; just look at some of the actor code in gzdoom.pk3 to see action function calls without parentheses.

In "[Variables and Data Types](https://github.com/jekyllgrim/ZScript_Basics/blob/master/Variables_and_data_types.md)", you can access the XY components of a 3D vector, as a 2D vector, using `.xy`.

**Comment by jekyllgrim** [comment]
> In "Classes Instead of Actors", it says you can't have a class that inherits from nothing. This isn't true;

I'll make a wording more precise on that.

> In "Anonymous Functions", it says you need to include a pair of empty parentheses at the end to call a function.

You _have_ to use parentheses when callign a function from inside an anonymous function. You can test it pretty easily yourself. You'll get "Function 'functionname' used without ()." otherwise.
