### ISSUE TITLE
Ambiguities in "Custom functions" section

### ISSUE THREAD

**Issue by Kzer-Za** [jekyllgrim/ZScript_Basics#2]
In the end of this section there is an example of custom version of A_MonsterRefire. The Missile state has `TNT1 A 0 A_MonsterRefire(5,"AttackEnd");`

Isn't it supposed to be `CustomMonsterRefire(5,"AttackEnd")`?

Also, the first condition in the function CustomMonsterRefire checks whether the monster has run out of ammo. However, I don't see anywhere the value of `monstermag` being decreased. For me, at least, it seems confusing. Maybe it's supposed to be decreased after A_CPosAttack? Then what the code should be? Something like:

```
CPAS F 2 A_CPosAttack;
TNT1 A 0 {monstermag--;}
```

?

And, by the way, isn't it better to check `if (monstermag <= 0)`?

**Comment by jekyllgrim** [comment]
This is correct, I pasted the custom function but didn't change the main code of the monster. I just pushed the fixes; thanks for noticing.
